name: 定时处理ADgk.txt文件

on:
  push:
    branches:
      - main

jobs:
  process_adgk_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout代码仓库内容
        uses: actions/checkout@v2

      - name: 下载ADgk.txt文件
        run: mkdir -p temp && cd temp && wget -q https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt

      - name: 处理ADgk.txt文件
        run: cd temp && sed '/^.\{1024,\}/d' ADgk.txt > ../ADgk.txt

      - name: 提交更改到仓库
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git commit -am "定时处理ADgk.txt文件"
          git push
