name: 定时处理easylist.txt

on:
  push:
    branches:
      - main

jobs:
  update_easylist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download easylist.txt
        run: curl -o easylist.txt https://easylist-downloads.adblockplus.org/easylist.txt

      - name: Process and compare easylist.txt
        run: |
          sed -i '/^.{1024,}/d' easylist.txt
          if diff --brief easylist.txt ${{ github.workspace }}/easylist.txt >/dev/null; then
            echo "easylist.txt 文件一致"
            echo "$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') - easylist.txt 文件一致" >> ${{ github.workspace }}/log/log.txt
          else
            cp easylist.txt ${{ github.workspace }}/easylist.txt
            echo "easylist.txt 文件已更新"
            echo "* $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') - easylist.txt 文件已更新" >> ${{ github.workspace }}/README.md
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update easylist.txt"
          git push
