name: 定时处理easylist.txt

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and process easylist.txt
        run: |
         curl -o easylist_downloaded.txt https://easylist-downloads.adblockplus.org/easylist.txt
         sed '/^.\{1024,\}/d' easylist_downloaded.txt > easylist_filtered.txt

      - name: Compare files
        id: compare
        run: |
          if ! cmp --silent easylist_filtered.txt ${{ github.workspace }}/easylist.txt; then
           echo "Files are different. Updating easylist.txt"
           mv easylist_filtered.txt ${{ github.workspace }}/easylist.txt
           processed_lines=$(grep -c '^.\{1024,\}' easylist_downloaded.txt)
           if [ -z "$processed_lines" ]; then
             processed_lines=0
           fi
           echo "* $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') - easylist.txt 文件已更新，处理了 $processed_lines 行" >> ${{ github.workspace }}/README.md
          else
           processed_lines=$(grep -c '^.\{1024,\}' easylist_downloaded.txt)
           if [ -z "$processed_lines" ]; then
              processed_lines=0
           fi
           echo "Files are the same. No action required."
           echo "$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') - easylist.txt 文件无更新，处理了 $processed_lines 行" >> ${{ github.workspace }}/log/log.txt
          fi

      - name: Clean up downloaded file
        run: rm easylist_downloaded.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add easylist.txt log/log.txt README.md
          git commit -m "Update easylist.txt"
          git push
